// youtubecontent/loginusingsocialmedia/src/Navbar.jsx
import { useAuth0 } from "@auth0/auth0-react";
import React from "react";
import { Link, useNavigate } from "react-router-dom";
import ContactMe from "./ContactMe";
import MyImage from "./MyImage";
import Home from "./Home";


function Navbar() {
  const navigate = useNavigate();
  const {
    isLoading,
    isAuthenticated,
    error,
    loginWithRedirect,
    logout: auth0Logout,
    user,
  } = useAuth0();

  const login = () => {
    loginWithRedirect({
      appState: { returnTo: "/" },
    });
  };

  const signup = () => {
    loginWithRedirect({
      authorizationParams: { screen_hint: "sign_up" },
      appState: { returnTo: "/" },
    });
  };
  const logout = () => {
    auth0Logout({ logoutParams: { returnTo: window.location.origin } });
  };

  return (
    <>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            Navbar
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <Link class="nav-link active" aria-current="page" to="/">
                  Home
                </Link>
              </li>
              <li class="nav-item">
                <Link
                  class="nav-link active"
                  aria-current="page"
                  to="/contactme"
                >
                  Contact Me
                </Link>
              </li>

              <li class="nav-item">
                <Link class="nav-link active" aria-current="page" to="/myimage">
                  My Image
                </Link>
              </li>
            </ul>

            {isLoading ? (
              <span>Loading ...</span>
            ) : isAuthenticated ? (
              <div className="d-flex align-items-center gap-2">
                <span className="me-2"> {user.name || user.email} </span>
                <button className="btn btn-danger btn-sm" onClick={logout}>
                  Logout
                </button>
              </div>
            ) : (
              <div className="d-flex gap-2">
                <button className="btn btn-primary btn-sm" onClick={signup}>
                  Signup
                </button>
                <button className="btn btn-success btn-sm" onClick={login}>
                  Login
                </button>
              </div>
            )}
          </div>
        </div>
      </nav>
    </>
  );
}

export default Navbar;

// project/WeatherAPP-main/frontend/src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthenticationService } from '../service/authentication.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  
  
  constructor(private authService:AuthenticationService, private router:Router) { }

  ngOnInit(): void {
    // const profile_name = this.authService.getUsername();
    
  }

  isLoggedIn():boolean{
    return this.authService.isLoggedIn();

  }
  profile_name :string = this.authService.getUsername();
  
  
  

  logout(){
    this.authService.logout();
    
    this.router.navigate(["/login"]);
  }
}

<nav class="navbar navbar-expand-lg b">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><img
        src="https://icon-library.com/images/android-weather-icon/android-weather-icon-24.jpg" alt="" height="40px"
        width="40px"></a>

    <button  class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span  class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li *ngIf="isLoggedIn()" class="nav-item ms-5">
          <a style="color: white;" class="nav-link active" aria-current="page" routerLink="/dashboard">Home</a>
        </li>
        <li *ngIf="isLoggedIn()" class="nav-item ms-5">
          <i style="color: white;" class="nav-link" routerLink='/listCities' class="material-icons"
            id="pointer">favorite</i>
        </li>
        <li  *ngIf="!isLoggedIn()" id="navLogin" routerLink='/login' class="nav-item ms-5">
          <a style="color: white;" class="nav-link active" aria-current="page" >Login</a>
        </li>
        <li class="nav-item ms-5">
          <a *ngIf="isLoggedIn()" (click)="logout()" style="margin-left: 800px; color: white;" class="nav-link " id="logout">Logout</a>
        </li>


        

        <!-- <form class="d-flex nav-item" role="search" #form="ngForm" >
            <input style="width:35rem;" class="form-control me-2 ms-5" type="search" [(ngModel)]="cityName" placeholder="Search" aria-label="Search" name="cityName">
          
          <button class="btn btn-outline-dark" (click)="searchValue()" >Search</button>
        </form> -->




        <!-- <li class="nav-item ms-5 dropdown">
          
          <a *ngIf="isLoggedIn()" (click)="logout()" style="margin-left: 200px; color: white;" class="nav-link" href="#" 
            role="button" >
            logout
          </a> -->
          
          

          <!-- <a *ngIf="!isLoggedIn()" style="margin-left: 200px; color: white;" class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
            role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User Name
          </a> -->

          <!-- <ul style="margin-left: 200px; color: white;" class="dropdown-menu col-sm-3  col-md-5"
            aria-labelledby="navbarDropdown">
            <div *ngIf="!isLoggedIn()">
            <li><a class="dropdown-item " routerLink="/login">Login</a></li>
            <li><a class="dropdown-item " routerLink="/signup">signUp</a></li></div>
            <div *ngIf="isLoggedIn()">
              <li><a (click)="logout()" class="dropdown-item">Logout</a></li>
            </div>

          </ul> -->
        <!-- </li> -->


      </ul>


    </div>
  </div>
</nav>


<router-outlet></router-outlet>
